# Generated by Django 4.2.5 on 2023-09-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_tweet_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
