# Generated by Django 4.2.5 on 2023-09-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tweet',
        ),
        migrations.AddField(
            model_name='tweet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_post', to='twitter.tag'),
        ),
    ]
