# Generated by Django 4.2.5 on 2023-09-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_remove_tag_tweet_tweet_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_word',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
